// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalHosting_64130107.Models;

#nullable disable

namespace RentalHosting_64130107.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241213143538_FixChiTietHopDongId")]
    partial class FixChiTietHopDongId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalHosting_64130107.Models.ChiTietHopDongModel_64130107", b =>
                {
                    b.Property<int>("ChiTietHopDongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietHopDongId"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HopDongId")
                        .HasColumnType("int");

                    b.Property<int>("HostingId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietHopDongId");

                    b.HasIndex("HopDongId");

                    b.HasIndex("HostingId");

                    b.ToTable("ChiTietHopDong");
                });

            modelBuilder.Entity("RentalHosting_64130107.Models.HopDongModel_64130107", b =>
                {
                    b.Property<int>("HopDongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HopDongId"));

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("HopDongId");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("RentalHosting_64130107.Models.HostingModel_64130107", b =>
                {
                    b.Property<int>("HostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostingId"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHosting")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HostingId");

                    b.ToTable("Hosting");
                });

            modelBuilder.Entity("RentalHosting_64130107.Models.LoaiHostingModel_64130107", b =>
                {
                    b.Property<int>("LoaiHostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiHostingId"));

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiHostingId");

                    b.ToTable("LoaiHosting");
                });

            modelBuilder.Entity("RentalHosting_64130107.Models.NguoiDungModel_64130107", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungId"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiDungId");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("RentalHosting_64130107.Models.ChiTietHopDongModel_64130107", b =>
                {
                    b.HasOne("RentalHosting_64130107.Models.HopDongModel_64130107", "HopDong")
                        .WithMany("ChiTietHopDong")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalHosting_64130107.Models.HostingModel_64130107", "Hosting")
                        .WithMany()
                        .HasForeignKey("HostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("Hosting");
                });

            modelBuilder.Entity("RentalHosting_64130107.Models.HopDongModel_64130107", b =>
                {
                    b.Navigation("ChiTietHopDong");
                });
#pragma warning restore 612, 618
        }
    }
}
